### ISSUE TITLE
How to use this with typescript?

### ISSUE THREAD

**Issue by sohrabsaran** [Tomekmularczyk/react-router-global-history#18]
Is there any types package available to install for compatibility with typescript?

**Comment by sohrabsaran** [comment]
npm i --save-dev @types/react-router-global-history
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-router-global-history - Not found
npm ERR! 404
npm ERR! 404  '@types/react-router-global-history@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sohra\AppData\Roaming\npm-cache\_logs\2021-04-10T04_49_22_818Z-debug.log

**Comment by Tomekmularczyk** [comment]
hey @sohrabsaran this package is quite outdated and I don't think it should be used anymore. There are other ways to achieve the same - by using hooks, or by creating custom history. https://reactrouter.com/web/api/Router/history-object
