### ISSUE TITLE
Has anyone got this to work with typescript?

### ISSUE THREAD

**Issue by GobbaFish** [Tomekmularczyk/react-router-global-history#3]
It doesn't appear to have a dts file and i am struggling generating one.

**Comment by dnknitro** [comment]
If anyone is interested, the `index.d.ts` for the module should look like this:
`declare module 'react-router-global-history' {
	import * as H from 'history'

	export const ReactRouterGlobalHistory: React.ComponentType<Pick<any, string | number | symbol>, any>;
	export default function getHistory(): H.History;
}`

**Comment by souvikcodefrags** [comment]
I have used the following .d.ts file in my React+TS code and it works. My app is created using create-react-app. I created a new file called **src/react-router-global-history.d.ts** and added the following code:

```
/// <reference types="node" />
/// <reference types="react" />
/// <reference types="react-dom" />

// import { any } from 'expect'; 
import { History } from 'history'

declare module 'react-router-global-history' {
    export const ReactRouterGlobalHistory: React.ComponentType<any>;
    export default function getHistory(): History;
}

```

Thanks to @dnknitro  and his code above.

**Comment by Tomekmularczyk** [comment]
@souvikcodefrags thanks for the typings I have added them and release 1.1.0 version. Although I believe now the correct approach to access history instead of using this lib would be to do:

```
import { createHistory } from 'history'

export const history = createHistory()

<Router history={history}>
</Router>
```

and just import `history` wherever you need

**Comment by souvikcodefrags** [comment]
@Tomekmularczyk My issue was that I was not getting history.push in app.tsx and in some modals which do not have a route. The other components with routes were having history normally. I will try your history import in app.tsx and the modals. I will post the findings.
